"""Administrative meeting protocol builder.

Flat 9-section format (T3.3, 2026-04-23) matching EPAM IT's
production prompt schema. Sections in DOCX render order:
    1. Title + meeting date
    2. Participants
    3. Meeting goal (if stated)
    4. Brief summary (3-7 sentences)
    5. Topics (bullets, neutral phrasing)
    6. Decisions (with speaker + evidence)
    7. Tasks (with owner + optional deadline + evidence)
    8. Open questions (with speaker + evidence)
    9. Risks (with speaker + evidence) — separate from open questions
   10. Stenogram (verbatim aligned-transcript turns)

LLM emits flat lists; parser does no department canonicalisation
beyond cleaning empty values. This replaces the earlier department-
grouped layout (HR/Finance/IT/...). Legacy department fields are still
recognised by the formatter for protocols generated by older runs
(see formatter._format_administrative_docx).
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any, Optional

from backend.engine.protocols.schemas import (
    AdministrativeProtocol,
    CourtHearingTurn,
    FlatProtocolItem,
    ProtocolResult,
    TopicSummary,
)

logger = logging.getLogger(__name__)


# =====================================================================
# Prompt construction
# =====================================================================

def build_prompt(
    transcript_text: str,
    language: str = "ru",
    meeting_context: str = "",
) -> list[dict]:
    """Build the Ollama chat prompt for an administrative meeting.

    Flat 9-section schema (T3.3, 2026-04-23) matching the EPAM IT
    team's production prompt verbatim, with two extensions:
      * `meeting_date` field at top (we already populate this).
      * `evidence` carried per-item (the IT prompt also requires this).

    Risks are kept as a separate top-level key (per IT and per
    user 2026-04-23 decision) — they answer "what's blocking us"
    while open_questions answers "what's unanswered". Different
    semantics, different sections.

    Args:
        transcript_text: Formatted transcript.
        language: "ru" or "en" — admin meetings are ru-only in practice.
        meeting_context: User-provided context.
    """
    return _build_practical_prompt(transcript_text, meeting_context)

    # 2026-05-04 prompt rewrite (task #44). Replaces the heavy
    # "ты секретарь, не выдумывай, лучше вернуть меньше" prompt with
    # an industry-pattern direct prompt modeled on Anthropic Meeting
    # Scribe + Notion AI Meeting Notes + OpenAI Cookbook guidance.
    #
    # Why we rewrote: the previous prompt had three layers of defense
    # (defensive persona + strict evidence requirement + verification
    # pass that deletes) that combined multiplicatively — producing
    # protocols with 2-3 decisions on hour-long meetings that had 15.
    # User feedback (2026-05-04): IT team's protocol with same Gemma 4
    # 26B model but simpler prompt produces noticeably more useful
    # output. Confirmed by 2025-2026 industry research: every leading
    # meeting AI (Otter, Fireflies, Notion, Teams, Anthropic Scribe)
    # uses direct task instruction without defensive persona framing.
    #
    # Key differences from the old prompt:
    # 1. No "ты секретарь" persona — direct task instruction.
    # 2. Implicit decisions ARE decisions: "давайте перенесём",
    #    "ну хорошо, делаем так" count. Previous prompt explicitly
    #    excluded these, which lost most real-world decisions.
    # 3. Owner/deadline are nice-to-have, not required. User said
    #    2026-05-04: "людей и сроки мы найдём потом как проставить".
    # 4. Evidence remains in schema but is descriptive (transcript
    #    quote helping the user verify), not gatekeeping. The
    #    verification pass (task #45) uses it to MARK confidence,
    #    not to delete items.
    # 5. Few-shot examples for decision/task/open_question give the
    #    model concrete grounding (research: few-shot is the single
    #    highest-leverage prompt change for extraction tasks).
    system = (
        "Извлеки структурированный протокол из стенограммы "
        "административного совещания. Твоя цель — помочь коллеге, "
        "который не присутствовал на встрече, понять её итоги.\n"
        "\n"
        "Извлекай ВСЁ существенное: явные и неявные решения, поручения "
        "и договорённости, открытые вопросы, риски и блокеры.\n"
        "Лучше включить сомнительный пункт с пометкой опорной цитаты — "
        "пользователь проверит и удалит ненужное вручную.\n"
        "\n"
        "ФОРМАТ ОТВЕТА — JSON со следующей плоской схемой (9 ключей "
        "верхнего уровня, без вложенных группировок):\n"
        "{\n"
        '  "meeting_date": "ДД.ММ.ГГГГ или \\"нет\\" если в стенограмме отсутствует",\n'
        '  "meeting_goal": "цель встречи, если явно или ясно сформулирована, иначе \\"нет\\"",\n'
        '  "summary": "3-7 предложений связного краткого содержания: какие темы обсуждались, какие итоги",\n'
        '  "participants": ["имя или роль участника", ...],\n'
        '  "topics": ["короткая нейтральная формулировка темы", ...],\n'
        '  "decisions": [\n'
        '    {"text": "суть решения", "speaker": "кто принял или предложил, иначе пусто", "evidence": "короткая цитата из стенограммы", "confidence": "high|medium|low"}\n'
        '  ],\n'
        '  "tasks": [\n'
        '    {"text": "описание поручения или договорённости", "owner": "кому, иначе пусто", "deadline": "срок, иначе пусто", "evidence": "короткая цитата", "confidence": "high|medium|low"}\n'
        '  ],\n'
        '  "open_questions": [\n'
        '    {"text": "формулировка нерешённого вопроса", "speaker": "кто поднял, иначе пусто", "evidence": "короткая цитата", "confidence": "high|medium|low"}\n'
        '  ],\n'
        '  "risks": [\n'
        '    {"text": "проблема, блокер или негативный сценарий", "speaker": "кто озвучил, иначе пусто", "evidence": "короткая цитата", "confidence": "high|medium|low"}\n'
        '  ]\n'
        "}\n"
        "\n"
        "CONFIDENCE — оценивай каждый decision/task/open_question/risk:\n"
        "• high — явное и однозначное: есть прямой маркер «решили», "
        "«договорились», «утверждаем»; либо очевидное согласие на "
        "конкретное предложение; либо явно поставленная задача с "
        "исполнителем\n"
        "• medium — ясно из контекста, но без явного маркера: "
        "«давайте сделаем так», «ну окей»; либо задача без явного "
        "исполнителя; либо открытый вопрос; либо озвученный риск\n"
        "• low — выведено из обсуждения, неоднозначно, опорная цитата "
        "слабая\n"
        "Используй low щедро — пользователь увидит low-элементы с "
        "пометкой и решит, оставить или удалить.\n"
        "\n"
        "ЧТО СЧИТАТЬ РЕШЕНИЕМ (важно — мы хотим зафиксировать решения, "
        "а не упустить их):\n"
        "Решение — это любая зафиксированная договорённость о действии "
        "или изменении статуса. Сюда входят:\n"
        "• Явные маркеры: «решили», «договорились», «принято», «утверждаем»\n"
        "• Согласие на предложение: «давайте перенесём» — решение перенести; "
        "«ну окей, делаем так» — решение сделать; «согласен» в ответ "
        "на предложение — решение принять предложение\n"
        "• Отказ или отсрочка: «пока не делаем», «отложили», «не будем» — "
        "это тоже решение\n"
        "• Делегирование: «пусть Иванов возьмёт» — решение поручить Иванову\n"
        "Не решение: размышления вслух, риторические вопросы, гипотезы, "
        "обсуждение вариантов без явного выбора.\n"
        "\n"
        "ЧТО СЧИТАТЬ ПОРУЧЕНИЕМ:\n"
        "Поручение — это конкретное действие, которое кто-то взял или "
        "получил на исполнение. Если исполнитель не назван, всё равно "
        "включи поручение и оставь owner пустым — пользователь "
        "проставит вручную. Если срок не назван — оставь deadline "
        "пустым.\n"
        "\n"
        "ЧТО СЧИТАТЬ ОТКРЫТЫМ ВОПРОСОМ:\n"
        "То, что обсуждали, но не закрыли в этой встрече: «нужно подумать», "
        "«вернёмся к этому», «непонятно как сделать», заданный вопрос "
        "без ответа.\n"
        "\n"
        "ЧТО СЧИТАТЬ РИСКОМ:\n"
        "Угроза, блокер или возможный негативный сценарий, явно "
        "озвученный участником. Например: «если не успеем — клиент уйдёт», "
        "«это может выйти за бюджет», «зависит от внешнего фактора».\n"
        "\n"
        "EVIDENCE:\n"
        "Для каждого decision/task/open_question/risk приведи в поле "
        "evidence короткую цитату из стенограммы (5-15 слов) — это "
        "помогает пользователю быстро найти источник в записи.\n"
        "Если короткой однозначной цитаты нет, всё равно включи "
        "элемент — приведи самую близкую фразу или короткий пересказ.\n"
        "\n"
        "PARTICIPANTS:\n"
        "Если оператор явно перечислил участников в КОНТЕКСТЕ ВСТРЕЧИ "
        "ниже (строка «Участники совещания: …»), используй именно этот "
        "список как источник имён без проверки.\n"
        "\n"
        "ЯЗЫК:\n"
        "Все поля — только на русском. Имена собственные, бренды, "
        "технические термины оставляй в оригинале.\n"
        "\n"
        "ВЫВОД:\n"
        "Ответь ТОЛЬКО JSON-объектом. Никаких markdown-блоков, никаких "
        "комментариев. Точно эти 9 ключей верхнего уровня."
    )

    if meeting_context:
        system += (
            "\n\nКОНТЕКСТ ВСТРЕЧИ (добавочная информация от оператора, "
            "используй только если согласуется со стенограммой):\n"
            f"{meeting_context}"
        )

    user = (
        "Стенограмма административного совещания:\n\n"
        f"{transcript_text}"
    )

    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def _build_practical_prompt(
    transcript_text: str,
    meeting_context: str = "",
) -> list[dict]:
    """Build the v1.0 practical admin protocol prompt.

    The product direction is "less report about the meeting, more what
    to remember and do". The DOCX should become a useful work product:
    participants plus a single list of practical takeaways backed by
    short transcript evidence.
    """
    system = (
        "Extract a practical administrative meeting protocol from the "
        "transcript. The goal is NOT to write a report about the meeting. "
        "The goal is to help a colleague quickly understand what must be "
        "remembered, checked, decided, or done.\n\n"
        "Output only JSON with this shape:\n"
        "{\n"
        '  "meeting_date": "DD.MM.YYYY or empty",\n'
        '  "participants": ["names from the operator context, if provided"],\n'
        '  "items": [\n'
        "    {\n"
        '      "type": "decision|task|open_question|risk|thesis",\n'
        '      "text": "short practical takeaway in Russian",\n'
        '      "owner": "responsible person/department, or empty",\n'
        '      "deadline": "deadline, or empty",\n'
        '      "speaker": "who proposed/confirmed/raised it, or empty",\n'
        '      "evidence_quote": "5-20 words from the transcript",\n'
        '      "timestamp": "HH:MM:SS or MM:SS if visible, or empty",\n'
        '      "confidence": "high|medium|low"\n'
        "    }\n"
        "  ]\n"
        "}\n\n"
        "What to include in items:\n"
        "- explicit and implicit decisions;\n"
        "- tasks and assignments, even if owner/deadline are missing;\n"
        "- important agreements and management theses;\n"
        "- open questions that must not be lost;\n"
        "- risks, blockers, or problems that require attention.\n\n"
        "Task owner inference:\n"
        "- If the owner is explicitly named, use that person or department.\n"
        "- If the owner is not named but the discussion is clearly about a "
        "department, function, or participant role from the operator context, "
        "fill owner with that department/person and set confidence to medium "
        "or low.\n"
        "- If the speaker says a task in a generic way (for example, "
        "\"need to prepare\", \"let's check\", \"we should send\"), infer the "
        "owner from the current discussed unit: HR tasks -> HR, IT tasks -> IT, "
        "finance tasks -> Finance, litigation/admin/document tasks -> the "
        "relevant department/person from context.\n"
        "- If there is no reliable context, leave owner empty.\n\n"
        "Deadline inference:\n"
        "- If a deadline is explicitly stated, use it.\n"
        "- If no deadline is stated but this is an ordinary operational task, "
        "use \"1-2 недели\" and set confidence to medium or low.\n"
        "- If the task is urgent or phrased as immediate, use \"1 неделя\".\n"
        "- If the task is complex, requires approvals, several teams, or "
        "document drafting/coordination, use \"до 1 месяца\".\n"
        "- If even this is too uncertain, leave deadline empty.\n\n"
        "Coverage rule:\n"
        "- Do not return a top-10 summary. Scan the transcript "
        "chronologically from beginning to end.\n"
        "- For long administrative meetings, a useful protocol often has "
        "15-35 items per hour. A 90-120 minute meeting may legitimately "
        "contain 25-60 items.\n"
        "- Include narrow local points if they may later become document "
        "drafting material. The user will remove excess items manually.\n"
        "- Do not merge separate decisions just because they belong to the "
        "same broad topic.\n\n"
        "Do not create separate sections for goal, summary, topics, risks, "
        "questions, or transcript. Everything useful goes into items.\n"
        "Prefer completeness over excessive caution. If a point is useful "
        "but not fully certain, include it with confidence=low.\n"
        "Do not invent facts. Each item must have a short evidence_quote "
        "from the transcript or the closest short paraphrase if the ASR text "
        "is too noisy.\n"
        "Write all user-facing fields in Russian. Keep names, brands, and "
        "technical terms as spoken.\n"
    )
    if meeting_context:
        system += (
            "\nOperator-provided context. Treat the participant list here "
            "as authoritative if present:\n"
            f"{meeting_context}\n"
        )
    user = (
        "Administrative meeting transcript:\n\n"
        f"{transcript_text}"
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def _practical_response_format_schema() -> dict[str, Any]:
    """Ollama structured-output schema for the practical admin layout."""
    confidence = {"type": "string", "enum": ["high", "medium", "low"]}
    item_type = {
        "type": "string",
        "enum": ["decision", "task", "open_question", "risk", "thesis"],
    }
    practical_item = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "type": item_type,
            "text": {"type": "string"},
            "owner": {"type": "string"},
            "deadline": {"type": "string"},
            "speaker": {"type": "string"},
            "evidence_quote": {"type": "string"},
            "timestamp": {"type": "string"},
            "confidence": confidence,
        },
        "required": [
            "type",
            "text",
            "owner",
            "deadline",
            "speaker",
            "evidence_quote",
            "timestamp",
            "confidence",
        ],
    }
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "meeting_date": {"type": "string"},
            "participants": {"type": "array", "items": {"type": "string"}},
            "items": {"type": "array", "items": practical_item},
        },
        "required": ["meeting_date", "participants", "items"],
    }


def practical_items_response_format_schema() -> dict[str, Any]:
    """Structured-output schema for an items-only recall pass."""
    base = _practical_response_format_schema()
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "items": base["properties"]["items"],
        },
        "required": ["items"],
    }


def build_practical_recall_prompt(
    *,
    window_transcript: str,
    existing_items: list[str],
    meeting_context: str = "",
    window_label: str = "",
) -> list[dict]:
    """Build a focused recall prompt for one chronological window.

    The primary full-transcript call is good at finding the largest
    takeaways, but long admin meetings often need a second pass over
    smaller windows so local decisions and tasks are not compressed away.
    This prompt returns additional candidates only; Python deduplicates.
    """
    existing = "\n".join(f"- {item}" for item in existing_items[:80])
    if not existing:
        existing = "- none"

    system = (
        "You are doing a recall pass for an administrative meeting "
        "protocol. The previous pass may have missed useful local points. "
        "Your job is to scan this time window carefully and extract "
        "additional practical items.\n\n"
        "Return JSON only, with this shape:\n"
        "{\n"
        '  "items": [\n'
        "    {\n"
        '      "type": "decision|task|open_question|risk|thesis",\n'
        '      "text": "practical takeaway in Russian",\n'
        '      "owner": "responsible person/department, or empty",\n'
        '      "deadline": "deadline, or empty",\n'
        '      "speaker": "who proposed/confirmed/raised it, or empty",\n'
        '      "evidence_quote": "5-20 words from this transcript window",\n'
        '      "timestamp": "HH:MM:SS or MM:SS if visible, or empty",\n'
        '      "confidence": "high|medium|low"\n'
        "    }\n"
        "  ]\n"
        "}\n\n"
        "Rules:\n"
        "- Do not summarize the whole window in one item. Extract separate "
        "decisions, tasks, risks, open questions, and useful theses.\n"
        "- Prefer over-inclusion. If useful but uncertain, include it with "
        "confidence=low.\n"
        "- Do not repeat an existing item unless this window contains a "
        "more specific separate point.\n"
        "- If the window truly has no practical content, return an empty "
        "items array.\n"
        "- For tasks, infer owner from the discussed department/person when "
        "the transcript or operator context makes it reasonably clear. Use "
        "confidence=medium or confidence=low for inferred owners.\n"
        "- For tasks without an explicit deadline, infer a practical default "
        "when useful: \"1 неделя\" for urgent items, \"1-2 недели\" for normal "
        "operational items, \"до 1 месяца\" for complex/cross-team items. If "
        "uncertain, leave deadline empty.\n"
        "- User-facing text must be Russian.\n"
    )
    if meeting_context:
        system += (
            "\nOperator context. Treat participant names here as "
            "authoritative if present:\n"
            f"{meeting_context}\n"
        )

    user = (
        f"Window: {window_label or 'chronological window'}\n\n"
        "Existing extracted items, do not duplicate:\n"
        f"{existing}\n\n"
        "Transcript window:\n\n"
        f"{window_transcript}"
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def response_format_schema() -> dict[str, Any]:
    """Ollama structured-output schema for the flat admin protocol.

    Kept hand-written instead of using the Pydantic schema because the
    LLM should only generate the extraction fields. Stenogram turns,
    legacy department blocks, and renderer-only defaults are assembled
    by Python after parsing.
    """
    return _practical_response_format_schema()

    confidence = {"type": "string", "enum": ["high", "medium", "low"]}

    attributed_item = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "text": {"type": "string"},
            "speaker": {"type": "string"},
            "evidence": {"type": "string"},
            "confidence": confidence,
        },
        "required": ["text", "speaker", "evidence", "confidence"],
    }

    task_item = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "text": {"type": "string"},
            "owner": {"type": "string"},
            "deadline": {"type": "string"},
            "evidence": {"type": "string"},
            "confidence": confidence,
        },
        "required": ["text", "owner", "deadline", "evidence", "confidence"],
    }

    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "meeting_date": {"type": "string"},
            "meeting_goal": {"type": "string"},
            "summary": {"type": "string"},
            "participants": {
                "type": "array",
                "items": {"type": "string"},
            },
            "topics": {
                "type": "array",
                "items": {"type": "string"},
            },
            "decisions": {
                "type": "array",
                "items": attributed_item,
            },
            "tasks": {
                "type": "array",
                "items": task_item,
            },
            "open_questions": {
                "type": "array",
                "items": attributed_item,
            },
            "risks": {
                "type": "array",
                "items": attributed_item,
            },
        },
        "required": [
            "meeting_date",
            "meeting_goal",
            "summary",
            "participants",
            "topics",
            "decisions",
            "tasks",
            "open_questions",
            "risks",
        ],
    }


def build_verification_prompt(
    protocol_text: str,
    transcript_text: str,
    language: str = "ru",
) -> list[dict]:
    """Verification pass for administrative meeting JSON.

    Drops items without transcript support. Never adds new items. Fully
    Russian-language instructions (2026-04-23 rewrite) matching the
    IT team's prompt style for Gemma 4 26B.
    """
    system = (
        "Ты строгий фактчекер протокола административного совещания в "
        "формате JSON. Твоя единственная задача — удалить элементы, "
        "которые не подтверждаются стенограммой. Новые элементы НЕ "
        "добавляй. Формулировки НЕ переписывай.\n"
        "\n"
        "Структура протокола: 9 ключей верхнего уровня — meeting_date, "
        "meeting_goal, summary, participants, topics, decisions, tasks, "
        "open_questions, risks. Сохрани этот точный набор ключей.\n"
        "\n"
        "ПРАВИЛА (строго):\n"
        "1. Для каждого элемента в decisions, tasks, open_questions, "
        "risks проверь, что в стенограмме есть фраза, близкая к полю "
        "evidence или text. Если такой фразы нет — УДАЛИ элемент.\n"
        "2. У decisions, open_questions, risks ОБЯЗАТЕЛЕН непустой "
        "speaker. Если speaker пустой или явно выдуман — УДАЛИ "
        "элемент.\n"
        "3. У task ОБЯЗАТЕЛЕН непустой owner. Если owner пустой — "
        "УДАЛИ элемент. Если owner — это \"нет\", но в тексте задачи "
        "явно есть исполнитель, перенеси исполнителя в owner.\n"
        "4. Если decision не имеет в стенограмме явного маркера "
        "(«решили», «договорились», «принято решение», «утверждаем», "
        "«фиксируем» или аналогичного) — УДАЛИ элемент. Неявное "
        "согласие решением не считается.\n"
        "5. Если task заявляет срок (deadline), которого нет в "
        "стенограмме — замени значение deadline на \"нет\", но элемент "
        "не удаляй.\n"
        "6. Если в стенограмме нет явного поручения, а task — это "
        "обсуждение, идея, вариант или намерение, УДАЛИ элемент.\n"
        "7. Если open_question на самом деле был разрешён в "
        "стенограмме (дан ответ, принято решение), УДАЛИ элемент.\n"
        "8. Если risk — это обычная рабочая сложность без признака "
        "проблемы/блокера/негативного исхода, УДАЛИ элемент.\n"
        "9. Если evidence явно выдуман или очевидно не совпадает с "
        "текстом стенограммы, УДАЛИ элемент.\n"
        "10. participants НЕ ТРОГАЙ. Список участников формируется "
        "отдельно (оператор предоставляет его в контексте); проверка "
        "по стенограмме не требуется. Оставь participants ровно "
        "таким, каким он пришёл на вход.\n"
        "11. summary, meeting_goal, topics НЕ ТРОГАЙ. Они уже "
        "проверены при первичной генерации. Только если summary "
        "содержит явные галлюцинации (конкретные факты, которых нет "
        "в стенограмме), удали соответствующее предложение.\n"
        "12. НЕ добавляй новые элементы. НЕ усиливай и не смягчай "
        "формулировки. Можно только удалять элементы или обнулять "
        "deadline.\n"
        "13. Сохрани точный набор ключей верхнего уровня (все 9). "
        "Все текстовые поля оставь на русском языке.\n"
        "14. При сомнении выбирай удаление. Лучше удалить сомнительный "
        "элемент, чем оставить недостоверный.\n"
        "\n"
        "ФОРМАТ ВЫВОДА:\n"
        "- Ответь ТОЛЬКО исправленным JSON-объектом.\n"
        "- Никаких markdown-блоков, никаких комментариев, никакого "
        "текста вне JSON."
    )

    max_transcript = 20000
    truncated = transcript_text[:max_transcript]
    user = (
        "ПРОТОКОЛ JSON ДЛЯ ПРОВЕРКИ:\n\n"
        f"{protocol_text}\n\n"
        "---\n\n"
        "СТЕНОГРАММА:\n\n"
        f"{truncated}"
    )

    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


# =====================================================================
# Parsing
# =====================================================================

_CONTEXT_ATTENDEES_RE = re.compile(
    r"Участники\s+совещания\s*:\s*([^\n\r.]+)",
    re.IGNORECASE,
)


def _participants_from_context(meeting_context: Optional[str]) -> list[str]:
    """Extract participant names from operator-provided context.

    Looks for the marker 'Участники совещания: X, Y, Z' which is emitted
    by the frontend UploadPage when the user checks attendee boxes. Names
    are split by comma/semicolon and trimmed. Used as a fallback when the
    LLM's participants field is empty — the operator's list is
    authoritative because it's from a curated checklist, not inferred.
    """
    if not meeting_context:
        return []
    match = _CONTEXT_ATTENDEES_RE.search(meeting_context)
    if not match:
        return []
    raw = match.group(1)
    names = [n.strip() for n in re.split(r"[,;]+", raw)]
    return [n for n in names if n]


def _clean_str(value: Any) -> str:
    """Treat 'нет' / 'none' / 'null' / 'n/a' / '-' as empty.

    The flat-schema prompt requires the LLM to use \"нет\" as the
    canonical empty value, so the parser maps those back to empty
    strings before they reach the formatter.
    """
    text = str(value or "").strip()
    if text.lower() in ("нет", "none", "null", "n/a", "-"):
        return ""
    return text


def _absorb_flat_items(
    raw_items: Any,
    speaker_field: str = "speaker",
    has_owner: bool = False,
    has_deadline: bool = False,
    kind: str = "thesis",
) -> list[FlatProtocolItem]:
    """Convert an LLM-emitted JSON list of dicts into FlatProtocolItem
    instances. Filters out entries with empty text. Tolerates partial
    fields per the schema (decisions/open_questions/risks need speaker,
    tasks need owner instead).
    """
    out: list[FlatProtocolItem] = []
    if not isinstance(raw_items, list):
        return out
    for entry in raw_items:
        if not isinstance(entry, dict):
            continue
        text = _clean_str(entry.get("text"))
        if not text:
            continue
        speaker = _clean_str(entry.get(speaker_field, "")) if speaker_field else ""
        evidence = _clean_str(entry.get("evidence"))
        owner = None
        if has_owner:
            owner_clean = _clean_str(entry.get("owner"))
            owner = owner_clean if owner_clean else None
        deadline = None
        if has_deadline:
            deadline_clean = _clean_str(entry.get("deadline"))
            deadline = deadline_clean if deadline_clean else None
        # Confidence label (task #45). Tolerant parser — anything not
        # in the {high, medium, low} set defaults to "medium" so a
        # malformed LLM output still produces a renderable protocol.
        confidence_raw = (
            _clean_str(entry.get("confidence", "")).lower()
        )
        if confidence_raw in ("high", "medium", "low"):
            confidence = confidence_raw  # type: ignore[assignment]
        else:
            confidence = "medium"
        out.append(
            FlatProtocolItem(
                kind=kind,
                text=text,
                speaker=speaker,
                evidence=evidence,
                owner=owner,
                deadline=deadline,
                confidence=confidence,
            )
        )
    return out


def _normalise_item_kind(value: Any) -> str:
    """Return a supported practical item kind."""
    raw = str(value or "").strip().lower()
    aliases = {
        "decision": "decision",
        "decisions": "decision",
        "task": "task",
        "action": "task",
        "action_item": "task",
        "open_question": "open_question",
        "question": "open_question",
        "risk": "risk",
        "blocker": "risk",
        "thesis": "thesis",
        "takeaway": "thesis",
        "agreement": "decision",
    }
    return aliases.get(raw, "thesis")


def _absorb_practical_items(raw_items: Any) -> list[FlatProtocolItem]:
    """Convert practical v1.0 JSON items into FlatProtocolItem."""
    out: list[FlatProtocolItem] = []
    if not isinstance(raw_items, list):
        return out
    for entry in raw_items:
        if not isinstance(entry, dict):
            continue
        text = _clean_str(entry.get("text"))
        if not text:
            continue
        confidence_raw = _clean_str(entry.get("confidence", "")).lower()
        confidence = (
            confidence_raw
            if confidence_raw in ("high", "medium", "low")
            else "medium"
        )
        owner = _clean_str(entry.get("owner"))
        deadline = _clean_str(entry.get("deadline"))
        out.append(
            FlatProtocolItem(
                kind=_normalise_item_kind(
                    entry.get("type", entry.get("kind", "thesis"))
                ),
                text=text,
                speaker=_clean_str(entry.get("speaker")),
                evidence=_clean_str(
                    entry.get("evidence_quote", entry.get("evidence"))
                ),
                timestamp=_clean_str(entry.get("timestamp")),
                owner=owner or None,
                deadline=deadline or None,
                confidence=confidence,  # type: ignore[arg-type]
            )
        )
    return out


def parse_practical_items(raw_text: str) -> list[FlatProtocolItem]:
    """Parse an items-only practical recall response."""
    parsed = _extract_json(raw_text)
    if not parsed:
        return []
    return _absorb_practical_items(parsed.get("items"))


def parse_response(
    raw_text: str,
    aligned: Optional[list] = None,
    meeting_context: Optional[str] = None,
) -> ProtocolResult:
    """Parse the flat 9-section LLM JSON into an AdministrativeProtocol.

    The LLM emits 9 top-level keys per the prompt schema; each item
    list is converted to FlatProtocolItem with text/speaker/evidence
    plus task-only owner/deadline. Empty values default to empty
    strings or None per the model.

    The aligned transcript populates the stenogram `turns` field
    (verbatim ground truth, not LLM-generated). meeting_context is
    scanned for the operator's attendee list as a fallback when the
    LLM returns empty participants.

    Args:
        raw_text: Raw LLM output (JSON).
        aligned: List of AlignedSegment for stenogram turns.
        meeting_context: User-provided context string. Scanned for
            'Участники совещания: ...' fallback.

    Returns:
        ProtocolResult with AdministrativeProtocol payload.
    """
    parsed = _extract_json(raw_text) or {}

    meeting_date = _clean_str(parsed.get("meeting_date"))
    meeting_goal = _clean_str(parsed.get("meeting_goal"))
    summary = _clean_str(parsed.get("summary"))

    participants_raw = parsed.get("participants") or []
    participants: list[str] = []
    if isinstance(participants_raw, list):
        for entry in participants_raw:
            cleaned = _clean_str(entry)
            if cleaned:
                participants.append(cleaned)

    # Fallback: if the LLM returned empty participants but the
    # operator's context has a 'Участники совещания: X, Y, Z' list,
    # use that list. The operator picked these names from a checklist
    # so they are authoritative — no need to verify against transcript.
    if not participants:
        fallback = _participants_from_context(meeting_context)
        if fallback:
            logger.info(
                "LLM returned empty participants; using %d operator-provided "
                "names from context", len(fallback),
            )
            participants = fallback

    topics_raw = parsed.get("topics") or []
    topics: list[str] = []
    if isinstance(topics_raw, list):
        for entry in topics_raw:
            cleaned = _clean_str(entry)
            if cleaned:
                topics.append(cleaned)

    # Practical v1.0 schema: one unified items list. Older/legacy
    # LLM output may still contain flat buckets; those are absorbed
    # below and merged into items for the new formatter.
    items = _absorb_practical_items(parsed.get("items"))

    # Decisions, open_questions, risks each take {text, speaker, evidence}.
    # Tasks take {text, owner, deadline, evidence} (no speaker — owner
    # is the meaningful field for who's responsible).
    decisions = _absorb_flat_items(parsed.get("decisions"), kind="decision")
    tasks = _absorb_flat_items(
        parsed.get("tasks"),
        speaker_field="",  # tasks don't carry speaker; owner is what matters
        has_owner=True,
        has_deadline=True,
        kind="task",
    )
    open_questions = _absorb_flat_items(
        parsed.get("open_questions"), kind="open_question"
    )
    risks = _absorb_flat_items(parsed.get("risks"), kind="risk")

    if items:
        # Keep old buckets populated for API/UI compatibility.
        decisions = [item for item in items if item.kind == "decision"]
        tasks = [item for item in items if item.kind == "task"]
        open_questions = [
            item for item in items if item.kind == "open_question"
        ]
        risks = [item for item in items if item.kind == "risk"]
    else:
        items = [
            *decisions,
            *tasks,
            *open_questions,
            *risks,
        ]

    # Build stenogram turns from the aligned transcript. Not sourced
    # from the LLM — this is verbatim ground truth, one turn per
    # aligned segment. start_s is captured for [HH:MM:SS] DOCX render.
    turns: list[CourtHearingTurn] = []
    if aligned:
        for seg in aligned:
            text = (getattr(seg, "text", "") or "").strip()
            if not text:
                continue
            label = (
                getattr(seg, "speaker_name", None)
                or getattr(seg, "speaker_id", None)
                or "Говорящий"
            )
            start_s = getattr(seg, "start", None)
            try:
                start_s = float(start_s) if start_s is not None else None
            except (TypeError, ValueError):
                start_s = None
            turns.append(
                CourtHearingTurn(
                    speaker=str(label).strip(),
                    text=text,
                    start_s=start_s,
                )
            )

    payload = AdministrativeProtocol(
        title="Протокол административного совещания",
        meeting_date=meeting_date,
        meeting_goal=meeting_goal,
        summary=summary,
        participants=participants,
        topics=topics,
        items=items,
        decisions=decisions,
        tasks=tasks,
        open_questions=open_questions,
        risks=risks,
        # Legacy department field stays empty for new flat-schema runs.
        # Formatter detects this and uses the new flat renderer.
        departments=[],
        turns=turns,
    )
    return ProtocolResult(meeting_type="administrative", payload=payload)


# =====================================================================
# Shared JSON extractor
# =====================================================================

def _extract_json(raw: str) -> Optional[dict[str, Any]]:
    """Extract the first top-level JSON object from raw LLM output."""
    if not raw:
        return None
    text = raw.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```\s*$", "", text)
    try:
        result = json.loads(text)
        if isinstance(result, dict):
            return result
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{[\s\S]*\}", text)
    if match:
        try:
            result = json.loads(match.group(0))
            if isinstance(result, dict):
                return result
        except json.JSONDecodeError as exc:
            logger.warning("Failed to parse fallback JSON block: %s", exc)
    logger.warning("Administrative LLM output was not valid JSON; returning empty")
    return None


# =====================================================================
# Map-reduce topic-segmented protocol (Sprint 2026-04-30, task #35)
# =====================================================================
#
# Two-step LLM process replacing the single-call flat 9-section path
# for administrative meetings:
#
#   Step 1 (boundary detection): one Gemma call asking "split the
#     transcript into thematic segments". Returns JSON of {name,
#     start_idx, end_idx} ranges.
#
#   Step 2 (per-topic summary): for each topic range, one Gemma call
#     asking for {discussion, decisions, tasks, open_questions}
#     scoped to that topic only. Smaller prompts → better attention,
#     more items extracted, more topic-relevant grounding.
#
# Risks remain at the protocol level (cross-cutting). Stenogram comes
# from the aligned transcript, not from the LLM. Topic_summaries
# populates the new field; flat decisions/tasks/questions are also
# populated as the union of per-topic items so the existing flat
# renderer has data when topic-segmented rendering is disabled or the
# JSON parse fails.
#
# Speed cost: 1 + N Gemma calls vs 2 (extract + verify) in the flat
# path. On a 50-min meeting with ~8 topics and 60s/call this is
# roughly +6 min — acceptable for a quality jump on the protocol the
# user actually keeps.

# Number transcript segments and emit "[idx] Speaker: text" lines so
# the LLM can return integer indices unambiguously. The boundary call
# uses these indices; the per-topic call slices the same transcript.
def _format_indexed_transcript(aligned: list[Any]) -> tuple[str, list[Any]]:
    """Return (LLM-friendly text, ordered seg list).

    Filters out empty segments so the indices the LLM receives match
    the indices we'll slice with later. Returns the ordered list so
    callers don't have to re-filter.
    """
    rows: list[str] = []
    kept: list[Any] = []
    for seg in aligned or []:
        text = (getattr(seg, "text", "") or "").strip()
        if not text:
            continue
        speaker = (
            getattr(seg, "speaker_name", None)
            or getattr(seg, "speaker_id", None)
            or "Говорящий"
        )
        idx = len(kept)
        rows.append(f"[{idx}] {speaker}: {text}")
        kept.append(seg)
    return "\n".join(rows), kept


def build_topic_boundaries_prompt(indexed_transcript: str) -> list[dict]:
    """Step-1 prompt: ask the LLM to detect topic boundaries.

    The LLM sees an indexed transcript (one line per segment with a
    `[N] Speaker: text` prefix) and returns a JSON array of topic
    ranges. We tell it which fields to use, give a brief example,
    and constrain the output to JSON only.

    Topic granularity is intentionally coarse (~5-10 topics for a
    30-60min meeting). Splitting too fine produces tiny per-topic
    summaries that don't add value over the flat format.
    """
    system = (
        "Ты секретарь совещания и аналитик в Адвокатском Бюро ЕПАМ.\n"
        "Твоя задача — разделить стенограмму административного "
        "совещания на тематические сегменты.\n"
        "Каждый сегмент = одна крупная тема обсуждения "
        "(например: \"Подбор персонала\", \"Дебиторка по проектам\", "
        "\"IT-инфраструктура\", \"Конкретный клиент Русал\").\n"
        "Гранулярность — крупная: 5-10 тем на часовое совещание. "
        "Не дроби на мелкие подтемы.\n"
        "Темы не должны пересекаться: end_idx предыдущей темы "
        "должен быть равен start_idx следующей минус один. Все "
        "сегменты транскрипта должны попасть ровно в одну тему.\n"
        "Не выдумывай темы — основывайся ТОЛЬКО на содержании "
        "стенограммы.\n"
        "Ответ строго в формате JSON без Markdown, без пояснений.\n"
    )
    user = (
        "Раздели стенограмму на тематические сегменты. Верни JSON "
        "следующего вида:\n"
        "{\n"
        '  "topics": [\n'
        '    {"name": "Подбор персонала", "start_idx": 0, "end_idx": 24},\n'
        '    {"name": "Дебиторка по проектам", "start_idx": 25, "end_idx": 87},\n'
        '    {"name": "IT-инфраструктура", "start_idx": 88, "end_idx": 142}\n'
        "  ]\n"
        "}\n\n"
        "ИНДЕКСИРОВАННАЯ СТЕНОГРАММА:\n"
        f"{indexed_transcript}\n"
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def parse_topic_boundaries(
    raw: str, transcript_len: int,
) -> list[dict[str, Any]]:
    """Parse the topic-detection response into validated ranges.

    Drops topics with out-of-range or inverted indices. Clamps to
    the transcript length. Returns a list of {name, start_idx,
    end_idx} dicts; empty list on parse failure (caller should fall
    back to the flat single-topic path).
    """
    obj = _extract_json(raw)
    if not obj:
        return []
    raw_topics = obj.get("topics") if isinstance(obj, dict) else None
    if not isinstance(raw_topics, list):
        return []

    cleaned: list[dict[str, Any]] = []
    for t in raw_topics:
        if not isinstance(t, dict):
            continue
        name = str(t.get("name", "")).strip()
        try:
            start = int(t.get("start_idx", -1))
            end = int(t.get("end_idx", -1))
        except (TypeError, ValueError):
            continue
        if not name or start < 0 or end < start:
            continue
        # Clamp to transcript length so a hallucinated index doesn't
        # crash the slicer.
        start = min(start, transcript_len - 1)
        end = min(end, transcript_len - 1)
        if start <= end:
            cleaned.append({"name": name, "start_idx": start, "end_idx": end})
    return cleaned


def build_topic_summary_prompt(
    topic_name: str,
    indexed_segment: str,
    meeting_context: str = "",
) -> list[dict]:
    """Step-2 prompt: structured summary for one topic block.

    Same anti-hallucination contract as the flat-9-section prompt
    (no advice, no inferred speakers, evidence required) but scoped
    to a single topic — smaller window, sharper attention.
    """
    system = (
        "Ты секретарь совещания и аналитик в Адвокатском Бюро ЕПАМ.\n"
        "Тебе дан фрагмент стенограммы по одной теме. Извлеки "
        "только факты, которые можно подтвердить текстом.\n"
        "Не добавляй советы, рекомендации, объяснения. Не выдумывай "
        "людей, решения, сроки, статусы, риски, вопросы и задачи.\n"
        "Если по конкретному пункту нет данных — оставь массив пустым.\n"
        "Ответ строго в формате JSON без Markdown.\n"
        "Все текстовые поля должны быть на русском языке.\n"
    )
    context_block = ""
    if meeting_context.strip():
        context_block = (
            "\n\nКОНТЕКСТ СОВЕЩАНИЯ (от пользователя):\n"
            f"{meeting_context.strip()}\n"
        )
    user = (
        f"Тема: \"{topic_name}\"\n\n"
        "Структурируй обсуждение этой темы. Верни JSON:\n"
        "{\n"
        '  "discussion": "1-3 предложения о чём обсуждение, фактически",\n'
        '  "decisions": [{"text": "...", "speaker": "Иванов И.И.", "evidence": "цитата"}],\n'
        '  "tasks": [{"text": "...", "owner": "Иванов И.И.", "deadline": "ДД.ММ.ГГГГ или null", "evidence": "цитата"}],\n'
        '  "open_questions": [{"text": "...", "speaker": "Иванов И.И.", "evidence": "цитата"}]\n'
        "}\n\n"
        "Поля speaker / owner — точные имена из стенограммы. "
        "Поле evidence — короткая дословная цитата из этого фрагмента "
        "(до 15 слов). Если не можешь привести цитату — НЕ включай "
        "элемент.\n"
        f"{context_block}\n"
        "ФРАГМЕНТ СТЕНОГРАММЫ:\n"
        f"{indexed_segment}\n"
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def parse_topic_summary(raw: str, topic_name: str) -> TopicSummary:
    """Parse a single per-topic LLM response into a TopicSummary.

    On parse failure returns an empty TopicSummary with just the
    name set — the topic still appears in the protocol so the reader
    can audit the segmentation, but with no synthesised content.
    """
    obj = _extract_json(raw)
    if not obj:
        return TopicSummary(name=topic_name)

    discussion = str(obj.get("discussion", "")).strip()

    def _items(key: str, *, has_owner: bool, has_deadline: bool) -> list[FlatProtocolItem]:
        out: list[FlatProtocolItem] = []
        raw_items = obj.get(key)
        if not isinstance(raw_items, list):
            return out
        for it in raw_items:
            if not isinstance(it, dict):
                continue
            text = str(it.get("text", "")).strip()
            if not text:
                continue
            evidence = str(it.get("evidence", "")).strip()
            # Drop items without evidence — anti-hallucination policy
            # mirrors the flat-format verifier.
            if not evidence:
                continue
            speaker = str(it.get("speaker", "")).strip()
            owner = (
                str(it.get("owner", "")).strip()
                if has_owner else ""
            ) or None
            deadline_raw = it.get("deadline") if has_deadline else None
            deadline = (
                str(deadline_raw).strip()
                if isinstance(deadline_raw, str) and deadline_raw.strip()
                and deadline_raw.strip().lower() not in ("null", "none", "нет")
                else None
            )
            out.append(
                FlatProtocolItem(
                    text=text,
                    speaker=speaker,
                    evidence=evidence,
                    owner=owner,
                    deadline=deadline,
                )
            )
        return out

    return TopicSummary(
        name=topic_name,
        discussion=discussion,
        decisions=_items("decisions", has_owner=False, has_deadline=False),
        tasks=_items("tasks", has_owner=True, has_deadline=True),
        open_questions=_items(
            "open_questions", has_owner=False, has_deadline=False
        ),
    )


def assemble_topic_segmented_protocol(
    *,
    aligned: list[Any],
    meeting_date: str,
    meeting_goal: str,
    summary: str,
    participants: list[str],
    risks: list[FlatProtocolItem],
    topic_summaries: list[TopicSummary],
    meeting_context: str = "",
) -> ProtocolResult:
    """Build the final ProtocolResult for a topic-segmented admin meeting.

    Combines (a) the topic-segmented bodies into ``topic_summaries``,
    (b) flat decisions/tasks/open_questions as the UNION across topics
    so the legacy renderer still works as a fallback, (c) topic
    *names* into the legacy ``topics`` list, (d) verbatim stenogram
    turns from the aligned transcript.

    The formatter dispatches: when ``topic_summaries`` is non-empty
    it renders the topic-grouped layout; otherwise it falls back to
    the flat 9-section layout.
    """
    # Flatten per-topic items into the legacy unified lists. This
    # keeps backward-compat: an older formatter / frontend / external
    # consumer that doesn't know about topic_summaries still gets
    # readable decisions / tasks / questions.
    flat_decisions: list[FlatProtocolItem] = []
    flat_tasks: list[FlatProtocolItem] = []
    flat_questions: list[FlatProtocolItem] = []
    for t in topic_summaries:
        flat_decisions.extend(t.decisions)
        flat_tasks.extend(t.tasks)
        flat_questions.extend(t.open_questions)

    topic_names = [t.name for t in topic_summaries if t.name.strip()]

    turns: list[CourtHearingTurn] = []
    for seg in aligned or []:
        text = (getattr(seg, "text", "") or "").strip()
        if not text:
            continue
        label = (
            getattr(seg, "speaker_name", None)
            or getattr(seg, "speaker_id", None)
            or "Говорящий"
        )
        start_s = getattr(seg, "start", None)
        try:
            start_s = float(start_s) if start_s is not None else None
        except (TypeError, ValueError):
            start_s = None
        turns.append(
            CourtHearingTurn(
                speaker=str(label).strip(),
                text=text,
                start_s=start_s,
            )
        )

    payload = AdministrativeProtocol(
        title="Протокол административного совещания",
        meeting_date=meeting_date,
        meeting_goal=meeting_goal,
        summary=summary,
        participants=participants,
        topics=topic_names,
        decisions=flat_decisions,
        tasks=flat_tasks,
        open_questions=flat_questions,
        risks=risks,
        topic_summaries=topic_summaries,
        departments=[],
        turns=turns,
    )
    return ProtocolResult(meeting_type="administrative", payload=payload)


__all__ = [
    "build_prompt",
    "build_verification_prompt",
    "parse_response",
    "build_practical_recall_prompt",
    "parse_practical_items",
    "practical_items_response_format_schema",
    # Map-reduce (task #35)
    "_format_indexed_transcript",
    "build_topic_boundaries_prompt",
    "parse_topic_boundaries",
    "build_topic_summary_prompt",
    "parse_topic_summary",
    "assemble_topic_segmented_protocol",
]
